== Predeployment steps

Before you deploy the Partner Solution template, decide whether to use two Availability Zones or three, and whether to use a https://docs.microsoft.com/en-us/windows-server/failover-clustering/manage-cluster-quorum[file share witness^] or a full node. By default, this deployment creates one Exchange node in each Availability Zone. The file share witness launches in the same Availability Zone as the first Exchange node.

NOTE: Where possible, deploy this Partner Solution using three Availability Zones. This enables automatic failover of database availability groups (DAGs) without the need for manual intervention.

You can deploy a full Exchange node instead of a file share witness. In addition, you can specify whether to deploy the full node or the file share witness in a third Availability Zone. For more information about quorum models, refer to https://docs.microsoft.com/en-us/Exchange/high-availability/database-availability-groups/database-availability-groups?view=exchserver-2019#database-availability-group-quorum-models[Database availability group quorum models^].

In addition, you can deploy an internal Application Load Balancer to provide high availability that distributes traffic to the Exchange nodes. For this configuration, you must import a Secure Sockets Layer (SSL) certificate into AWS Certificate Manager (ACM) before you launch the template.